# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aed5962aa333b205c0146c4fb22c925b1a68a81e7d20211d3deac618fe1cceec363c2583dfd7ed63e12a98b3137f5f271603fd393d1e86fff303d9eb395e598

test:
  secret_key_base: 525594eddb1d4b72539a71e682f9c50a4a020aae4d1e9d88c9e41790a650cf15aef7643c6d737c3a3edfd09556c46b918280795973d775565afc218e233087b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
